// <auto-generated />
using AS3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AS3.Migrations
{
    [DbContext(typeof(Assignment3DbContext))]
    partial class Assignment3DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AS3.Models.UserModel.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Content = "Aliquid nesciunt eos dolores occaecati earum temporibus. Dolores et eveniet perferendis doloribus animi temporibus. Ipsa non quasi ut dolores dolorum. Velit officia dolorum. Facilis sunt ducimus inventore fugiat.",
                            Title = "Provident totam eos mollitia quo libero."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 9,
                            Content = "Saepe deleniti ducimus aliquid delectus perspiciatis consequatur deserunt explicabo ipsam. Sed cumque voluptatem. Quia quaerat veniam quasi aut aspernatur eius ipsum possimus. Porro perferendis sit vel.",
                            Title = "Voluptas nesciunt ratione nobis aut."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Content = "Et in quaerat similique in sunt suscipit. Earum sit et quos enim laboriosam. Natus itaque repellat odit suscipit. Delectus autem itaque et nisi. Quia vero quidem rerum aliquid sequi fugiat a.",
                            Title = "Eius perspiciatis nesciunt adipisci ut vero quidem saepe eos."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 9,
                            Content = "Voluptatem tenetur qui unde ratione. Aut iusto incidunt quae accusamus autem nam quo. Velit dolores praesentium est accusantium a.",
                            Title = "Ducimus nemo ab doloremque."
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 10,
                            Content = "Ex praesentium voluptas quis vel. Ipsa aut id. Quo quis accusamus mollitia. Tempora officiis sed enim impedit pariatur accusamus non harum sunt.",
                            Title = "Porro ea neque."
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 8,
                            Content = "Sit molestiae et mollitia esse eligendi est odit est sunt. Quia id alias asperiores cupiditate qui voluptates. Expedita officia nostrum dicta commodi sit libero.",
                            Title = "Ipsam repellendus eius omnis sunt iste harum."
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Content = "Sed provident ut quo. Minima sunt quaerat tempora. Provident perferendis ea.",
                            Title = "Incidunt consequatur dolorum quo a molestias magnam."
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 9,
                            Content = "Necessitatibus est omnis qui totam id iste. Quod illum sit quisquam. Iure earum quae velit. Ea ullam voluptas ratione quam porro recusandae sit.",
                            Title = "Assumenda harum incidunt cupiditate inventore quos quis."
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            Content = "Aperiam quas mollitia enim debitis magni. Nisi vero quo nulla voluptatem veniam tempore expedita sint omnis. Aut rerum est ipsam consequatur labore eum sequi. Consequatur laboriosam fugit nihil.",
                            Title = "Est explicabo rem perferendis consequatur nostrum."
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            Content = "Vel et aut iure ut. Corporis voluptate nulla vel qui debitis officia velit eius. Et quo aspernatur aliquid eveniet aliquam molestiae mollitia voluptates. Suscipit laborum sunt laudantium molestiae. Eum facilis similique quaerat. Dicta tempore similique quasi quod aut.",
                            Title = "Et aliquam consequatur dolorem rerum consequuntur."
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 10,
                            Content = "In eos dicta sapiente sunt dolores nemo amet. Culpa iste quis tempore aut minus qui nostrum maxime magni. Et distinctio repellat officia. Suscipit quod a culpa modi incidunt velit perferendis voluptatum cum.",
                            Title = "At nihil omnis eius quidem omnis adipisci est vel omnis."
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Content = "Quibusdam deleniti ab cumque fugit sapiente. Nam nostrum necessitatibus minima accusantium aut non libero repudiandae. Et eveniet ex. Odit aliquam provident aut cupiditate. Quia accusamus quasi recusandae incidunt recusandae soluta. Hic ut aspernatur.",
                            Title = "Natus magnam voluptas ex molestiae culpa voluptas provident voluptas praesentium."
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            Content = "Consequuntur qui at sit facere facilis et illo tenetur. Sit omnis nam similique doloremque earum autem incidunt. Repellendus accusamus dolorum. Laudantium eos dignissimos sed. Officiis in quo.",
                            Title = "Sit impedit ipsum perferendis quas ab quia adipisci quia."
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 7,
                            Content = "Consectetur similique nostrum iste voluptatem iusto perferendis nulla praesentium ad. Nulla praesentium sequi est nam omnis mollitia. Quos quidem magnam distinctio assumenda dolorem est ad. Qui minus dicta voluptatibus et at amet aut rerum aut. Voluptatem sapiente quisquam error praesentium voluptate a.",
                            Title = "Velit rerum et."
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 9,
                            Content = "Quasi consequatur occaecati expedita voluptas et dolorem culpa. Ut illo ut. Vel tempore eos et asperiores commodi aut. Occaecati ut eaque esse voluptatem eos blanditiis nostrum consequatur illum.",
                            Title = "Adipisci quis doloribus nostrum voluptas quas accusamus quia."
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 7,
                            Content = "Corporis tenetur quis eos adipisci nihil quod sunt rerum. Voluptatem velit est cupiditate harum cupiditate autem veniam. Nobis aut explicabo id itaque rerum pariatur ut perferendis. Non odio molestias vero harum placeat vero. Accusamus iure necessitatibus quis qui sit dolores. Quas quidem et qui consectetur expedita.",
                            Title = "Perferendis numquam ut occaecati et culpa suscipit veniam."
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            Content = "Ea sed nisi aut inventore. Cupiditate qui praesentium optio id id. Possimus quis aut voluptas qui quo. Molestiae sit ut. Molestias et sint consequatur. Accusantium est dolore sed molestias perspiciatis est libero.",
                            Title = "Qui consequatur dignissimos dolores necessitatibus doloremque maxime qui a quisquam."
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 2,
                            Content = "Ducimus eius ut numquam. Sit quasi voluptatem quia ut porro nam. Vitae quia qui. Incidunt esse neque dolorum voluptatem necessitatibus qui.",
                            Title = "Et nam tempora aliquam aut cum voluptate ducimus sit."
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            Content = "Atque rem et vel accusamus. Quas quia laudantium reprehenderit ducimus. Commodi assumenda voluptatibus blanditiis enim ducimus ab et placeat. Aliquam illum totam rerum amet dolor quam qui ratione voluptas. Dolores commodi mollitia beatae voluptas debitis sunt autem vel expedita. Dolorum totam sapiente aut placeat doloremque autem sint velit.",
                            Title = "Eveniet repellendus distinctio molestiae inventore esse vero hic aut velit."
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            Content = "Adipisci qui et soluta. Dolores magnam sed aut impedit ut ipsa. Esse animi nihil nobis. Impedit numquam reprehenderit iusto rerum ut. Laudantium consequatur ipsum consectetur est sed. Nostrum molestias nemo doloremque.",
                            Title = "Natus occaecati ipsa quos."
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            Content = "Eum assumenda tenetur consectetur voluptatem ipsum. Sapiente ex impedit omnis. At nostrum mollitia.",
                            Title = "Perferendis consequuntur quidem."
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 9,
                            Content = "Sit et mollitia dicta mollitia. Ducimus assumenda libero aut quia voluptatem eaque. Quidem atque voluptatem eveniet molestiae tenetur aperiam quam possimus inventore.",
                            Title = "Laborum eaque a quia laborum maiores harum impedit repellendus."
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 1,
                            Content = "Quis itaque ex voluptate nemo beatae natus aut odit dolorem. Voluptatibus rerum delectus consequatur voluptas laborum earum commodi sint quia. Eligendi sed exercitationem illo ea iusto. Ad facilis exercitationem.",
                            Title = "Nihil accusamus quae at."
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 5,
                            Content = "Dolorem voluptas voluptatem quis voluptatem fugiat eum eaque eos iusto. Sit quia qui similique. Nihil vero nesciunt maiores blanditiis ut et laborum quisquam vitae. Rerum quod enim repellat praesentium. Corrupti nihil voluptas labore repellat.",
                            Title = "Reprehenderit delectus architecto."
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 4,
                            Content = "Sint eum voluptas recusandae accusantium tempora ratione. Et a sed voluptate ut fuga. Ullam accusantium optio rerum saepe iste quae incidunt quo. Omnis aut dicta soluta ea quisquam. Maiores sit voluptatem est aut nihil.",
                            Title = "Aut quo fugit necessitatibus voluptates ea odio occaecati."
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 4,
                            Content = "Assumenda quidem vitae nobis dolorem quia. Sed odit optio et corrupti qui nobis id. Ut tempora tempore et sit id praesentium sed debitis.",
                            Title = "Inventore autem beatae et."
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 8,
                            Content = "Animi commodi sapiente. Voluptatibus architecto laboriosam quam nulla corporis quisquam soluta. Sint aliquid nam tempore ipsa aliquid voluptatem laboriosam.",
                            Title = "Occaecati eius adipisci voluptatem voluptas provident."
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 10,
                            Content = "Omnis consequuntur est quis nisi assumenda. Est in dolorum. Consequatur sed quibusdam cupiditate quia at quae in. Hic in et ipsum eos.",
                            Title = "Numquam similique itaque voluptates."
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 8,
                            Content = "Maxime dolor sapiente dolores soluta autem tempore velit ut consequuntur. Voluptas ducimus minus et hic illo possimus. Minima molestiae aspernatur dolorem quia fugiat cum. Aliquid autem minus est.",
                            Title = "Aliquam natus qui."
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 6,
                            Content = "Occaecati veritatis recusandae consequatur. Dicta dolor assumenda et molestias dolorem. Aut quae necessitatibus repellendus hic vero facilis. Necessitatibus eveniet voluptatum unde ut qui.",
                            Title = "Ut est ut aut ducimus non perferendis rerum sit."
                        });
                });

            modelBuilder.Entity("AS3.Models.UserModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Bernie.Waters@gmail.com",
                            Password = "t11ol4c_VT"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Lucienne.Bergnaum@gmail.com",
                            Password = "378eJq5Dvo"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Krista.Thiel21@gmail.com",
                            Password = "oik1Bf74Nz"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Gregory91@yahoo.com",
                            Password = "g1i17Qnbrl"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Delfina32@hotmail.com",
                            Password = "ja3pBSt3Yo"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Velma_Waelchi44@yahoo.com",
                            Password = "Hs1QfJwTzT"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Rosalyn.Beatty23@hotmail.com",
                            Password = "wkOMnEP4RA"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Maximilian7@yahoo.com",
                            Password = "yqlHNtIrQ1"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Jena71@gmail.com",
                            Password = "QDtU2XTHHV"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Jovanny.Cremin@yahoo.com",
                            Password = "EATNLE4nZj"
                        });
                });

            modelBuilder.Entity("AS3.Models.UserModel.Article", b =>
                {
                    b.HasOne("AS3.Models.UserModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
